### PR TITLE
Updating logic to create an alias .all for cluster admins to still vi…

### PR DESCRIPTION
**Pull request by ewolinetz**
…ew logs for deleted namespaces

This is to address https://bugzilla.redhat.com/show_bug.cgi?id=1316219

@jcantrill @sosiouxme PTAL

### CODE REVIEW

**Comment by jcantrill** [comment]
LGTM.

**Comment by ewolinetz** [comment]
There is an issue where if you have pre-existing indices they won't be added to the alias.

**Comment by ewolinetz** [comment]
PTAL

**Comment by ewolinetz** [comment]
@jimmidyson @jcantrill @richm @sosiouxme PTAL

**Comment by richm** [comment]
Can you provide 2 commits - the first one with just the whitespace changes, and the second with the actual code?

**Comment by ewolinetz** [comment]
@richm i forget that Atom does that... removed whitespace changes

**Comment by ewolinetz** [comment]
squashed commits

**Comment by ewolinetz** [comment]
[merge]

**Pull request merged**
