### PR TITLE
2.4.4.16 redo

### PR DESCRIPTION
**Pull request by jcantrill**
@rich This PR reverts all the changes related to the client upgrade, and integration tests.  And adds back in the fix that was introduced afterwards.  Please try this with your test.

### CODE REVIEW

**Comment by richm** [comment]
can you save that integration test code in a separate branch?

**Comment by lukas-vlcek** [comment]
Hey, wait a second ... how is this ... was it ... are we literally ... ?

**Comment by jcantrill** [comment]
@richm It exists as a commit point in the history so we can fetch it from there.  I'm hoping to get back around to it once I better understand what is different about the client and the SAR code

**Comment by richm** [comment]
ack

**Comment by jcantrill** [comment]
@richm   This test validates various formats of username to resolve username related issues.  We now hash the username in the roles and rolesmapping documents.
```
$ PUBLIC_MASTER_URL=https://192.168.122.89:8443 bundle exec cucumber --tags @elasticsearch
#encoding: utf-8
Feature: The openshift-elasticsearch-plugin supports multitenancy

  @elasticsearch
  Scenario Outline: A user is granted permission to access their projects  # features/elasticsearch.feature:5
    Given user <username> with the role of developer for project <project> # features/elasticsearch.feature:7
    And an application is generating logs in <project>                     # features/elasticsearch.feature:8
    And logs were collected for the <project> project                      # features/elasticsearch.feature:9
    When they search for <project> logs                                    # features/elasticsearch.feature:10
    Then their access is not forbidden                                     # features/elasticsearch.feature:11

    Examples: 
      | username                                                      | project    |
      | simpleusername                                                | devproject |
      | foo@email.com                                                 | devproject |
      | CN=jdoe,OU=DL IT,OU=User Accounts,DC=example,DC=com           | devproject |
      | test\\username                                                | devproject |
      | CN=Lastname\\, Firstname,OU=Users,OU=TDBFG,DC=d2-tdbfg,DC=com | devproject |

5 scenarios (5 passed)
25 steps (25 passed)
0m28.923s

```

**Comment by jcantrill** [comment]
Merging as the only change is the comment here with test results

**Pull request merged**
