### PR TITLE
Upstream 24417

### PR DESCRIPTION
**Pull request by jcantrill**

### CODE REVIEW

**Comment by janstey** [comment]
So I *think* I know why the release job is failing (https://fabric8-ci.fusesource.com/view/release%20builds/job/openshift-elasticsearch-plugin-release-2.4.1.x/). There are open staging repos for a https://github.com/fabric8io/pipeline-test-project-dependency release that are blocked due to nexus warnings (missing sig, sources, javadoc). @rawlingsj can you drop the bad repos on oss.sonatype.org? I don't have privileges to see the fabric8 staging repos there. Thx!

**Comment by janstey** [comment]
Looks like it was just one staging repo:

[ERROR] 
[ERROR] Nexus Staging Rules Failure Report
[ERROR] ==================================
[ERROR] 
[ERROR] Repository "iofabric8-4772" failures
[ERROR]   Rule "javadoc-staging" failures
[ERROR]     * Missing: no javadoc jar found in folder '/io/fabric8/pipeline-test-project-dependency/1.1.28'
[ERROR]     * Missing: no javadoc jar found in folder '/io/fabric8/pipeline-test-project-dependency/null'
[ERROR]     * Missing: no javadoc jar found in folder '/io/fabric8/pipeline-test-project-dependency/2.2.0'
[ERROR]   Rule "signature-staging" failures
[ERROR]     * Missing Signature: '/io/fabric8/pipeline-test-project-dependency/1.1.28/pipeline-test-project-dependency-1.1.28.jar.asc' does not exist for 'pipeline-test-project-dependency-1.1.28.jar'.
[ERROR]     * Missing Signature: '/io/fabric8/pipeline-test-project-dependency/1.1.28/pipeline-test-project-dependency-1.1.28.pom.asc' does not exist for 'pipeline-test-project-dependency-1.1.28.pom'.
[ERROR]     * Missing Signature: '/io/fabric8/pipeline-test-project-dependency/null/pipeline-test-project-dependency-null.pom.asc' does not exist for 'pipeline-test-project-dependency-null.pom'.
[ERROR]     * Missing Signature: '/io/fabric8/pipeline-test-project-dependency/null/pipeline-test-project-dependency-null.jar.asc' does not exist for 'pipeline-test-project-dependency-null.jar'.
[ERROR]     * Missing Signature: '/io/fabric8/pipeline-test-project-dependency/2.2.0/pipeline-test-project-dependency-2.2.0.pom.asc' does not exist for 'pipeline-test-project-dependency-2.2.0.pom'.
[ERROR]     * Missing Signature: '/io/fabric8/pipeline-test-project-dependency/2.2.0/pipeline-test-project-dependency-2.2.0.jar.asc' does not exist for 'pipeline-test-project-dependency-2.2.0.jar'.
[ERROR]   Rule "sources-staging" failures
[ERROR]     * Missing: no sources jar found in folder '/io/fabric8/pipeline-test-project-dependency/1.1.28'
[ERROR]     * Missing: no sources jar found in folder '/io/fabric8/pipeline-test-project-dependency/null'
[ERROR]     * Missing: no sources jar found in folder '/io/fabric8/pipeline-test-project-dependency/2.2.0'

**Comment by janstey** [comment]
@jimmidyson @iocanel ^^^ you guys probably have privileges to drop that bad staging repo too?

**Comment by jcantrill** [comment]
@janstey @iocanel  new failure based on the job that runs against master https://fabric8-ci.fusesource.com/view/release%20builds/job/openshift-elasticsearch-plugin-release/63/console

**Comment by janstey** [comment]
@jcantrill latest release build worked. See http://repo1.maven.org/maven2/io/fabric8/elasticsearch/openshift-elasticsearch-plugin/2.4.4.19/

**Pull request merged**
