### PR TITLE
 Bug 1762572: bump kubernetes-client

### PR DESCRIPTION
**Pull request by jcantrill**
Resolve: https://bugzilla.redhat.com/show_bug.cgi?id=1762572

### CODE REVIEW

**Comment by jcantrill** [comment]
@richm @ewolinetz I believe CI is broken again.  
* Posted local tests: https://gist.github.com/jcantrill/62b1a8238424fc056e611377f8d74c56  
* Passing OAL: https://github.com/openshift/origin-aggregated-logging/pull/1785

Concerns merging?

**Comment by ewolinetz** [comment]
@jcantrill squash?

**Comment by jcantrill** [comment]
> @jcantrill squash?

dont want to squash. subsequent comments change the pom version like CI used to do

**Comment by richm** [comment]
sure - merge - just be sure to add it to the pile of tech debt . . .

**Comment by jcantrill** [comment]
merging per https://github.com/openshift/origin-aggregated-logging/pull/1785#issuecomment-555753306

**Pull request merged**
