### PR TITLE
Kibana user rewriting

### PR DESCRIPTION
**Pull request by ewolinetz**

### CODE REVIEW

**Comment by ewolinetz** [comment]
@jcantrill regarding the username hashing, that is this line: https://github.com/fabric8io/openshift-elasticsearch-plugin/pull/14/files#diff-33428050655bed70b01ac20b8db7fa9fR156

regarding the resource json files, they can be considered as samples; I wasn't sure if I would be using them and replacing the specific fields after reading them in or creating a document builder.. I'll move them to a location to reflect them being samples.

I'm not sure which line your first comment is referring to, there is no line number associated with it...  is it this line? https://github.com/fabric8io/openshift-elasticsearch-plugin/pull/14/files#diff-7a8c5fa1143836e1ad63eaeec49af5baR121

**Comment by jcantrill** [comment]
@ewolinetz  move them into the test resources.  First comment is to import static

**Comment by ewolinetz** [comment]
@sosiouxme made updates to handle the GetFieldMappingsResponse and Requests

**Comment by ewolinetz** [comment]
@jcantrill @sosiouxme PTAL - removed kibana seeding logic; now just rewrites kibana user indexes

**Comment by jcantrill** [comment]
@ewolinetz  LGTM. squash and merge

**Comment by ewolinetz** [comment]
@jcantrill squashed
[merge]

**Pull request merged**
