### PR TITLE
add support for a curator user for ES

### PR DESCRIPTION
**Pull request by richm**
Curator is the Elasticsearch tool that deletes/archives old indices.  It needs very specific access, so we need to create a new user and give that user very specific access.

### CODE REVIEW

**Comment by richm** [comment]
@ewolinetz PTAL

**Comment by ewolinetz** [comment]
this looks good to me, thoughts @jimmidyson ?

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
LGTM although I'm not quite sure how this plays into SearchGuard ACLs to allow the curator user to read & delete indices?

**Comment by ewolinetz** [comment]
Yes, this is so that we can use the Elastic Curator product to clean up logs and be allowed through Searchguard

**Comment by ewolinetz** [comment]
[merge]

**Comment by jcantrill** [comment]
@richm https://fabric8-ci.fusesource.com/view/release%20builds/job/openshift-elasticsearch-plugin-release/12/

**Pull request merged**
