### PR TITLE
Impl to auth by proxy header and fall back to client cert

### PR DESCRIPTION
**Pull request by jcantrill**
And make return 401 instead of 500 when cert auth fails.  @sosiouxme @ewolinetz @jimmidyson  please review

### CODE REVIEW

**Comment by jcantrill** [comment]
rebased and updated

**Comment by jcantrill** [comment]
@jimmidyson now this plugin depends upon searchguard, how do we get at it for the CI?

**Comment by jimmidyson** [comment]
You'll need to use a released dependency, not snapshot.

**Comment by jcantrill** [comment]
@jimmidyson @sosiouxme @ewolinetz  Updated pom.xml to use the release of SG.  Any takers for review?  Look at my sweet test I added too..

**Comment by ewolinetz** [comment]
sweet tests!  LGTM

**Comment by jimmidyson** [comment]
LGTM

**Comment by jimmidyson** [comment]
[merge]

**Comment by sosiouxme** [comment]
@jimmidyson can we get a nice maven release of this?

**Comment by jimmidyson** [comment]
Ah yeah -will do in the morning.

**Comment by jimmidyson** [comment]
@sosiouxme 0.3 released.

**Pull request merged**
